config/routes.rb
TLDR::Application.routes.draw do

  # Sign in/out
  get    'login' => 'session#new', as: :login
  post   'login' => 'session#create'
  delete 'logout' => 'session#destroy', as: :logout

  # Registration
  get  'register/:code' => 'registration#new', as: :register
  post 'register/:code' => 'registration#create'

  # Password reset
  get   'reset/:code' => 'password#edit', as: :reset
  put   'reset/:code' => 'password#update'
  patch 'reset/:code' => 'password#update'

  get 'privacy' => 'site#privacy'
  get 'terms'   => 'site#terms'
  get 'list'    => 'site#list'

  root 'site#main'

end

app/models/registrant.rb
class Registrant
  include Mongoid::Document
  include Mongoid::Timestamps
  
  field :id, type: String
  field :email, type: String
  field :expires_at, type: Time
end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps
  
  attr_accessor :password, :password_confirmation
  
  field :id, type: String
  
  field :name, type: String
  field :email, type: String
  
  field :salt, type: String
  field :fish, type: String
  
  field :code, type: String
  field :expires_at, type: Time
  
  before_save :encrypt_password
  
  validates :email, presence: true
  validates :email, uniqueness: { case_sensitive: false }
  validates :password, confirmation: true
  
  def authenticate(password)
    self.fish == BCrypt::Engine.hash_secret(password, self.salt)
  end
  
  private
  
  def encrypt_password
    if password.present?
      self.salt = BCrypt::Engine.generate_salt
      self.fish = BCrypt::Engine.hash_secret(password, self.salt)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user
  
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def is_authenticated?
    redirect_to login_url unless current_user
  end
end

app/controllers/password_controller.rb
class PasswordController < ApplicationController
  
  def edit
    @user = User.find_by(code: params[:code])
    puts
    puts @user.inspect
    puts
    if @user && @user.expires_at > Time.now
      render :edit
    else
      redirect_to login_url, error: "Sorry, your code has expired. Please try again."
    end
  end
  
  def update
    @user = User.find_by(code: params[:code])
    
    if @user.update_attributes(user_params)
      @user.code = nil
      @user.expires_at = nil
      @user.save
      
      session[:user_id] = @user.id
      redirect_to root_url, notice: "Your password has been updated."
    else
      flash.now[:error] = "Something went wrong. Please check your passwords and try again."
      render :edit
    end
  end
  
  private
  
  def user_params
    params.require(:user).permit(
      :password,
      :password_confirmation
    )
  end
end

app/controllers/registration_controller.rb
class RegistrationController < ApplicationController
  
  def new
    @registrant = Registrant.find_by(id: params[:code])
    
    if @registrant && @registrant.expires_at > Time.now
      render :new
    else
      redirect_to login_url, error: "Sorry, your code has expired. Please try again."
    end
  end
  
  def create
    @registrant = Registrant.find_by(id: params[:code])

    @user = User.new(user_params)
    @user.email = @registrant.email
    
    if @user.save
      @registrant.destroy
      
      session[:user_id] = @user.id
      redirect_to root_url, notice: "Thank you for registering!"
    else
      flash.now[:error] = "Something went wrong. Please check your data and try again."
      render :new
    end
  end
  
  private
  
  def user_params
    params.require(:user).permit(
      :name,
      :password,
      :password_confirmation
    )
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  before_action :is_authenticated?, only: [ :destroy ]

  def new
    redirect_to root_url if current_user
  end

  def create
    # is the password blank?
    if params[:user][:password].blank?
      if @user = User.find_by(email: params[:user][:email])
        @user.code = SecureRandom.urlsafe_base64
        @user.expires_at = Time.now + 1.day
        @user.save

        UserMailer.reset_email(@user, request).deliver

        flash.now[:notice] = "An email with instructions for " +
          "resetting your password has been sent to you."
        render :new
      else
        @registrant = Registrant.new
        @registrant.id = SecureRandom.urlsafe_base64
        @registrant.email = params[:user][:email]
        @registrant.expires_at = Time.now + 1.day
        @registrant.save

        UserMailer.registration_email(@registrant, request).deliver

        flash.now[:notice] = "An email with instructions for " +
          "completing your registration has been sent to you."
        render :new
      end
    else
      # attempt to authenticate
      @user = User.find_by(email: params[:user][:email])

      if @user && @user.authenticate(params[:user][:password])
        session[:user_id] = @user.id
        redirect_to root_url
      else
        render :new, error: "Unable to sign you in. Please try again."
      end
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_url, notice: "You've logged out."
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  before_action :is_authenticated?, only: [ :index ]
  
  def index
    @users = User.all.entries
  end
  
  def privacy
    
  end
  
  def terms
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_header.html.slim
.navbar.navbar-inverse.navbar-fixed-top
  .container
    span.navbar-brand.logo Home
    span.navbar-brand.logo About
    span.navbar-brand.logo Manifesto
    span.navbar-brand.logo Contact

app/views/layouts/_messages.html.slim
- flash.each do |name, message|
	- if message.is_a?(String)
		- noty_type = (name == :notice ? "success" : "error")
		- timeout = (name == :notice ? 4000 : false)
		javascript:
			$(function() {
				noty({
					layout: 'bottom',
					type: "#{noty_type}",
					text: "#{message}",
					timeout: "#{timeout}"
				});
			});

app/views/layouts/_navigation.html.slim
.navbar.navbar-inverse.navbar-fixed-top
  .container
    button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"
      span.icon-bar
      span.icon-bar
      span.icon-bar
    = link_to_unless_current "TLDR", root_url, class: "navbar-brand logo" do
      span.navbar-brand.logo TLDR
    .collapse.navbar-collapse
      ul.nav.navbar-nav.pull-right
        li
          = link_to "Sign out", logout_url, method: :delete, class: "logout-link"

app/views/layouts/_password.html.slim
javascript:
  $(function() {

    $('#show-password-button').on('click', function(e) {
      switch ($(this).data('state')) {
        case 'show':
          $(this).html( $(this).html().replace('Show','Hide') );
          $(this).removeClass('btn-danger').addClass('btn-warning');
          $('.showable-password').attr('type','text');
          $(this).data('state','hide');
          break;
        default:
          $(this).html( $(this).html().replace('Hide','Show') );
          $(this).removeClass('btn-warning').addClass('btn-danger');
          $('.showable-password').attr('type','password');
          $(this).data('state','show');
      }

      e.preventDefault();
    });
  });

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1.0"

    title TLDR

    = csrf_meta_tags

    = stylesheet_link_tag "application", media: "all"
    = javascript_include_tag "application"
  body
    #wrap
      - if current_user
        == render partial: 'layouts/navigation'
      - else
        == render partial: 'layouts/header'

      .container
        .page
          == yield

    #footer
      .container
        p.text-muted.credit
          => link_to "Privacy Policy", privacy_url
          ' •
          => link_to "Terms of Use", terms_url
          ' • © 2013 TLDR

    == render partial: 'layouts/messages'

app/views/password/edit.html.slim
.row
  .col-lg-4.col-lg-offset-4
    h1 Please choose a new password
    .row
      .col-lg-9
        = form_for :user, url: reset_url, method: :put, html: { role: "form" } do |f|
          .form-group
            = f.label :password
            = f.password_field :password, class: "form-control showable-password", placeholder: "Password"
          .form-group
            = f.label :password_confirmation
            = f.password_field :password_confirmation, class: "form-control showable-password", placeholder: "Type it again"
          .form-group
            => f.submit "Save", class: "btn btn-success"
            button#show-password-button.btn.btn-warning data-state="show" Show Passwords

== render partial: 'layouts/password'

app/views/session/new.html.slim
.row
  .col-lg-4.col-lg-offset-4
    ul.nav.nav-pills.login-options
      li.active
        a#login-pill href="#" Sign in
      li
        a#register-pill href="#" Register
      li
        a#reset-pill href="#" Reset Password
    = form_for :user, url: login_url, html: { role: "form", id: "loginform" } do |f|
      .row
        .col-lg-8
          fieldset
            legend Please sign in
            .form-group
              = f.label :email
              = f.text_field :email, class: "form-control", placeholder: "Email address"
            .form-group
              = f.label :password, id: 'password-label'
              = f.password_field :password, class: "form-control showable-password", placeholder: "Password"
            .form-group
              => f.submit "Sign in", class: "btn btn-success", id: 'submit-button'
              button#show-password-button.btn.btn-danger data-state="show" Show Password

javascript:
  $(function() {

    $('.login-options li a').on('click', function(e) {
      var elem = $(this)[0];
      var id = elem.id;

      $('.login-options li').removeClass('active');
      $(elem.parentNode).addClass('active');

      switch (id) {
        case 'register-pill':
          $('legend').html('Please enter your email');
          $('#password-label').hide();
          $('#user_password').hide();
          $('#show-password-button').hide();
          $('#submit-button').val('Register');
          break;
        case 'reset-pill':
          $('legend').html('Please enter your email');
          $('#password-label').hide();
          $('#user_password').hide();
          $('#show-password-button').hide();
          $('#submit-button').val('Reset');
          break;
        default:
          $('legend').html('Please sign in');
          $('#password-label').show();
          $('#user_password').show();
          $('#show-password-button').show();
          $('#submit-button').val('Sign in');
      }

      e.preventDefault();
    });

  });

== render partial: 'layouts/password'

app/views/site/index.html.slim
.row
  .col-lg-6.col-lg-offset-3
    table#users-table.table.table-bordered.table-striped
      caption Our users!
      thead
        tr
          th Name
          th Email
          th Created
      tbody
        - @users.each do |user|
          tr
            td #{user.name}
            td #{user.email}
            td #{user.created_at}

app/views/site/list.html.slim
.row
  .col-lg-6.col-lg-offset-3
    table#users-table.table.table-bordered.table-striped
      caption Our users!
      thead
        tr
          th Name
          th Email
          th Created
      tbody
        - @users.each do |user|
          tr
            td #{user.name}
            td #{user.email}
            td #{user.created_at}

app/views/site/privacy.html.slim
h1 Privacy Policy

app/views/site/terms.html.slim
h1 Terms of Use